Add support for profiling using compiler function instrumentation (#366)
* Added capability for fine grained profiling

* added functionality to do fine grained profiling

* Adding flag for profiler

* Put -lvnTools in target_link_libraries

* using generator expressions so that instrument functions are not used in every build

* ran clag-format

* got rid of warnings

* fixing problem with undefined reference to symbol 'dlclose@@GLIB_2.2.5

* clang format files

* used cmake-format

* fixing format

* fixing up formatting issues

* switching of TRACCC_PROFILE flag

* Revert "switching of TRACCC_PROFILE flag"

This reverts commit 8d20024a61a078d53bd00876e5a4cc5c60a3d443.

* fixed issue with generator expressions

* added feature to inst_nvtx.cpp to protect against platform specific function that are not available on other platform

* added feature to inst_nvtx.cpp to protect against platform specific function that are not available on other platform

* fixed formatting issues

* Updates

* minor changes

* Changes

* Changes

* Bring back colours

* Fixes

* Fix error

---------

Co-authored-by: Xola Mapekula <xola.mapekula@cern.ch>
Co-authored-by: Stephen Nicholas Swatman <stephen.nicholas.swatman@cern.ch>